# Generated by Django 4.2 on 2023-04-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='text',
            new_name='user',
        ),
    ]
